FROM nginx:alpine

WORKDIR /usr/share/nginx/html

# Copy survey static files to Nginx directory
COPY . .

# Use the provided Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]